name: Automatic Label Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  label_sync:
    uses: sapphiredev/.github/.github/workflows/reusable-labelsync.yml@main
