name: Release Updater

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  release-updater-linux-macos:
    name: Release updater Linux and MacOS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Package binaries
        run: bun run build

      - name: Upload prebuild asset
        uses: ./actions/prebuildArtifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: 'dist/*'

  release-updater-windows:
    name: Release updater Windows
    needs: release-updater-linux-macos
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install

      - name: Package binaries
        run: bun run build:windows

      - name: Upload prebuild asset
        uses: ./actions/prebuildArtifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: 'dist/*'
